// Code generated by Slice Machine. DO NOT EDIT.

import GridImageLeft from './GridImageLeft/index.svelte';
import GridImageRight from './GridImageRight/index.svelte';
import GridSelect from './GridSelect/index.svelte';
import Hero from './Hero/index.svelte';
import Image from './Image/index.svelte';
import MenuItems from './MenuItems/index.svelte';
import Search from './Search/index.svelte';
import Text from './Text/index.svelte';
import TextWithImage from './TextWithImage/index.svelte';
import VideoGameSearch from './VideoGameSearch/index.svelte';

export const components = {
	grid_image_left: GridImageLeft,
	grid_image_right: GridImageRight,
	grid_select: GridSelect,
	hero: Hero,
	image: Image,
	image_cards: MenuItems,
	search: Search,
	text: Text,
	text_with_image: TextWithImage,
	video_game_search: VideoGameSearch
};
