// Code generated by Slice Machine. DO NOT EDIT.

import BgPageSplitCards from './BgPageSplitCards/index.svelte';
import Eventcalendar from './Eventcalendar/index.svelte';
import Form from './Form/index.svelte';
import GeekTriviaScores from './GeekTriviaScores/index.svelte';
import GeekTriviaThemes from './GeekTriviaThemes/index.svelte';
import Googlemap from './Googlemap/index.svelte';
import GridSelect from './GridSelect/index.svelte';
import Hero from './Hero/index.svelte';
import HeroSmall from './HeroSmall/index.svelte';
import Image from './Image/index.svelte';
import MenuItems from './MenuItems/index.svelte';
import Imagewithtext from './Imagewithtext/index.svelte';
import LargeReso from './LargeReso/index.svelte';
import PageSplit from './PageSplit/index.svelte';
import PageSplitCards from './PageSplitCards/index.svelte';
import Reservation from './Reservation/index.svelte';
import Search from './Search/index.svelte';
import Text from './Text/index.svelte';
import TextCentered from './TextCentered/index.svelte';
import TextColumns from './TextColumns/index.svelte';
import TextWithImage from './TextWithImage/index.svelte';
import VideoGameSearch from './VideoGameSearch/index.svelte';

export const components = {
	bg_page_split_cards: BgPageSplitCards,
	dnd: Eventcalendar,
	form: Form,
	geek_trivia_scores: GeekTriviaScores,
	geek_trivia_themes: GeekTriviaThemes,
	googlemap: Googlemap,
	grid_select: GridSelect,
	hero: Hero,
	hero_small: HeroSmall,
	image: Image,
	image_cards: MenuItems,
	imagewithtext: Imagewithtext,
	large_reso: LargeReso,
	page_split: PageSplit,
	page_split_cards: PageSplitCards,
	reservation: Reservation,
	search: Search,
	text: Text,
	text_centered: TextCentered,
	text_columns: TextColumns,
	text_with_image: TextWithImage,
	video_game_search: VideoGameSearch
};
