// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & // Other fields
	{
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
	/**
	 * Label field in *Navigation → Links*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Optional - Label for the link
	 * - **API ID Path**: navigation.links[].label
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	label: prismic.RichTextField;

	/**
	 * Link field in *Navigation → Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Link for navigation item
	 * - **API ID Path**: navigation.links[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
	/**
	 * Links field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;

	/**
	 * stayplay field in *Navigation*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.stayplay
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	stayplay: prismic.RichTextField;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavigationDocumentData>,
	'navigation',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| LargeResoSlice
	| HeroSmallSlice
	| GeekTriviaThemesSlice
	| GeekTriviaScoresSlice
	| TextCenteredSlice
	| BgPageSplitCardsSlice
	| PageSplitCardsSlice
	| PageSplitSlice
	| TextColumnsSlice
	| ImagewithtextSlice
	| DndSlice
	| GooglemapSlice
	| ReservationSlice
	| FormSlice
	| VideoGameSearchSlice
	| GridSelectSlice
	| SearchSlice
	| HeroSlice
	| TextSlice
	| ImageSlice
	| ImageCardsSlice
	| TextWithImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Parent field in *Page*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.parent
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	parent: prismic.ContentRelationshipField<'page'>;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * logo field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>;

	/**
	 * Site Title field in *Settings*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Title of the site
	 * - **API ID Path**: settings.siteTitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	siteTitle: prismic.RichTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

export type AllDocumentTypes = NavigationDocument | PageDocument | SettingsDocument;

/**
 * Item in *BgPageSplitCards → Default → Primary → Card*
 */
export interface BgPageSplitCardsSliceDefaultPrimaryCardItem {
	/**
	 * Card Title field in *BgPageSplitCards → Default → Primary → Card*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bg_page_split_cards.default.primary.card[].card_title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	card_title: prismic.RichTextField;

	/**
	 * Card Content field in *BgPageSplitCards → Default → Primary → Card*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bg_page_split_cards.default.primary.card[].card_content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	card_content: prismic.RichTextField;

	/**
	 * Card Link field in *BgPageSplitCards → Default → Primary → Card*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bg_page_split_cards.default.primary.card[].card_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	card_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *BgPageSplitCards → Default → Primary*
 */
export interface BgPageSplitCardsSliceDefaultPrimary {
	/**
	 * Background field in *BgPageSplitCards → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bg_page_split_cards.default.primary.background
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	background: prismic.ImageField<never>;

	/**
	 * Title field in *BgPageSplitCards → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bg_page_split_cards.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Card field in *BgPageSplitCards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bg_page_split_cards.default.primary.card[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	card: prismic.GroupField<Simplify<BgPageSplitCardsSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for BgPageSplitCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BgPageSplitCardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BgPageSplitCardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BgPageSplitCards*
 */
type BgPageSplitCardsSliceVariation = BgPageSplitCardsSliceDefault;

/**
 * BgPageSplitCards Shared Slice
 *
 * - **API ID**: `bg_page_split_cards`
 * - **Description**: BgPageSplitCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BgPageSplitCardsSlice = prismic.SharedSlice<
	'bg_page_split_cards',
	BgPageSplitCardsSliceVariation
>;

/**
 * Default variation for Eventcalendar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DndSliceDefault = prismic.SharedSliceVariation<'default', Record<string, never>, never>;

/**
 * Slice variation for *Eventcalendar*
 */
type DndSliceVariation = DndSliceDefault;

/**
 * Eventcalendar Shared Slice
 *
 * - **API ID**: `dnd`
 * - **Description**: Dnd
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DndSlice = prismic.SharedSlice<'dnd', DndSliceVariation>;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
	/**
	 * form field in *Form → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: don't type here
	 * - **API ID Path**: form.default.primary.form
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	form: prismic.KeyTextField;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FormSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSlice = prismic.SharedSlice<'form', FormSliceVariation>;

/**
 * Default variation for GeekTriviaScores Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GeekTriviaScoresSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *GeekTriviaScores*
 */
type GeekTriviaScoresSliceVariation = GeekTriviaScoresSliceDefault;

/**
 * GeekTriviaScores Shared Slice
 *
 * - **API ID**: `geek_trivia_scores`
 * - **Description**: GeekTriviaScores
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GeekTriviaScoresSlice = prismic.SharedSlice<
	'geek_trivia_scores',
	GeekTriviaScoresSliceVariation
>;

/**
 * Default variation for GeekTriviaThemes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GeekTriviaThemesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *GeekTriviaThemes*
 */
type GeekTriviaThemesSliceVariation = GeekTriviaThemesSliceDefault;

/**
 * GeekTriviaThemes Shared Slice
 *
 * - **API ID**: `geek_trivia_themes`
 * - **Description**: GeekTriviaThemes
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GeekTriviaThemesSlice = prismic.SharedSlice<
	'geek_trivia_themes',
	GeekTriviaThemesSliceVariation
>;

/**
 * Default variation for Googlemap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GooglemapSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *Googlemap*
 */
type GooglemapSliceVariation = GooglemapSliceDefault;

/**
 * Googlemap Shared Slice
 *
 * - **API ID**: `googlemap`
 * - **Description**: Googlemap
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GooglemapSlice = prismic.SharedSlice<'googlemap', GooglemapSliceVariation>;

/**
 * Item in *GridSelect → Default → Primary → GridGroup*
 */
export interface GridSelectSliceDefaultPrimaryGridgroupItem {
	/**
	 * Image Text field in *GridSelect → Default → Primary → GridGroup*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: grid_select.default.primary.gridgroup[].image_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	image_text: prismic.RichTextField;

	/**
	 * GridImage field in *GridSelect → Default → Primary → GridGroup*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: grid_select.default.primary.gridgroup[].gridimage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	gridimage: prismic.ImageField<never>;

	/**
	 * GridLink field in *GridSelect → Default → Primary → GridGroup*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: grid_select.default.primary.gridgroup[].gridlink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	gridlink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *GridSelect → Default → Primary*
 */
export interface GridSelectSliceDefaultPrimary {
	/**
	 * GridGroup field in *GridSelect → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: grid_select.default.primary.gridgroup[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	gridgroup: prismic.GroupField<Simplify<GridSelectSliceDefaultPrimaryGridgroupItem>>;
}

/**
 * Default variation for GridSelect Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridSelectSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<GridSelectSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *GridSelect*
 */
type GridSelectSliceVariation = GridSelectSliceDefault;

/**
 * GridSelect Shared Slice
 *
 * - **API ID**: `grid_select`
 * - **Description**: GridSelect
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridSelectSlice = prismic.SharedSlice<'grid_select', GridSelectSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * Button Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.buttonLink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	buttonLink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Button Text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.buttonText
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttonText: prismic.KeyTextField;

	/**
	 * Background Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.backgroundImage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *HeroSmall → Default → Primary*
 */
export interface HeroSmallSliceDefaultPrimary {
	/**
	 * Text field in *HeroSmall → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_small.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * Button Link field in *HeroSmall → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_small.default.primary.buttonLink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	buttonLink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Button Text field in *HeroSmall → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_small.default.primary.buttonText
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttonText: prismic.KeyTextField;

	/**
	 * Background Image field in *HeroSmall → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_small.default.primary.backgroundImage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSmall Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSmallSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSmallSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeroSmall*
 */
type HeroSmallSliceVariation = HeroSmallSliceDefault;

/**
 * HeroSmall Shared Slice
 *
 * - **API ID**: `hero_small`
 * - **Description**: HeroSmall
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSmallSlice = prismic.SharedSlice<'hero_small', HeroSmallSliceVariation>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
	/**
	 * Image field in *Image → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Image → Banner → Primary*
 */
export interface ImageSliceBannerPrimary {
	/**
	 * Image field in *Image → Banner → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.banner.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Banner variation for Image Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceBanner = prismic.SharedSliceVariation<
	'banner',
	Simplify<ImageSliceBannerPrimary>,
	never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceBanner;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>;

/**
 * Item in *MenuItems → Default → Primary → Cards*
 */
export interface ImageCardsSliceDefaultPrimaryCardsItem {
	/**
	 * Image field in *MenuItems → Default → Primary → Cards*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Title field in *MenuItems → Default → Primary → Cards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * price field in *MenuItems → Default → Primary → Cards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: price
	 * - **API ID Path**: image_cards.default.primary.cards[].price
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	price: prismic.RichTextField;

	/**
	 * Text field in *MenuItems → Default → Primary → Cards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * notes field in *MenuItems → Default → Primary → Cards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].notes
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	notes: prismic.RichTextField;

	/**
	 * 86 item field in *MenuItems → Default → Primary → Cards*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_cards.default.primary.cards[].remove_items
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	remove_items: prismic.BooleanField;
}

/**
 * Primary content in *MenuItems → Default → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
	/**
	 * Heading field in *MenuItems → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;

	/**
	 * Cards field in *MenuItems → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	cards: prismic.GroupField<Simplify<ImageCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for MenuItems Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageCardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *MenuItems*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * MenuItems Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardsSlice = prismic.SharedSlice<'image_cards', ImageCardsSliceVariation>;

/**
 * Primary content in *Imagewithtext → Default → Primary*
 */
export interface ImagewithtextSliceDefaultPrimary {
	/**
	 * image field in *Imagewithtext → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: imagewithtext.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * text field in *Imagewithtext → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: imagewithtext.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for Imagewithtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImagewithtextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImagewithtextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Imagewithtext*
 */
type ImagewithtextSliceVariation = ImagewithtextSliceDefault;

/**
 * Imagewithtext Shared Slice
 *
 * - **API ID**: `imagewithtext`
 * - **Description**: Imagewithtext
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImagewithtextSlice = prismic.SharedSlice<'imagewithtext', ImagewithtextSliceVariation>;

/**
 * Default variation for LargeReso Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeResoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *LargeReso*
 */
type LargeResoSliceVariation = LargeResoSliceDefault;

/**
 * LargeReso Shared Slice
 *
 * - **API ID**: `large_reso`
 * - **Description**: LargeReso
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeResoSlice = prismic.SharedSlice<'large_reso', LargeResoSliceVariation>;

/**
 * Primary content in *PageSplit → Default → Primary*
 */
export interface PageSplitSliceDefaultPrimary {
	/**
	 * Text field in *PageSplit → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_split.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for PageSplit Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageSplitSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PageSplitSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *PageSplit*
 */
type PageSplitSliceVariation = PageSplitSliceDefault;

/**
 * PageSplit Shared Slice
 *
 * - **API ID**: `page_split`
 * - **Description**: PageSplit
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageSplitSlice = prismic.SharedSlice<'page_split', PageSplitSliceVariation>;

/**
 * Item in *PageSplitCards → Default → Primary → Cards*
 */
export interface PageSplitCardsSliceDefaultPrimaryCardsItem {
	/**
	 * CardTitle field in *PageSplitCards → Default → Primary → Cards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_split_cards.default.primary.cards[].cardtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	cardtitle: prismic.RichTextField;

	/**
	 * CardContent field in *PageSplitCards → Default → Primary → Cards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_split_cards.default.primary.cards[].cardcontent
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	cardcontent: prismic.RichTextField;

	/**
	 * CardLink field in *PageSplitCards → Default → Primary → Cards*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_split_cards.default.primary.cards[].cardlink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cardlink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * CardImage field in *PageSplitCards → Default → Primary → Cards*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_split_cards.default.primary.cards[].cardimage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cardimage: prismic.ImageField<never>;
}

/**
 * Primary content in *PageSplitCards → Default → Primary*
 */
export interface PageSplitCardsSliceDefaultPrimary {
	/**
	 * Title field in *PageSplitCards → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_split_cards.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Cards field in *PageSplitCards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_split_cards.default.primary.cards[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	cards: prismic.GroupField<Simplify<PageSplitCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for PageSplitCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageSplitCardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PageSplitCardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *PageSplitCards*
 */
type PageSplitCardsSliceVariation = PageSplitCardsSliceDefault;

/**
 * PageSplitCards Shared Slice
 *
 * - **API ID**: `page_split_cards`
 * - **Description**: PageSplitCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageSplitCardsSlice = prismic.SharedSlice<
	'page_split_cards',
	PageSplitCardsSliceVariation
>;

/**
 * Default variation for Reservation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReservationSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *Reservation*
 */
type ReservationSliceVariation = ReservationSliceDefault;

/**
 * Reservation Shared Slice
 *
 * - **API ID**: `reservation`
 * - **Description**: Reservation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReservationSlice = prismic.SharedSlice<'reservation', ReservationSliceVariation>;

/**
 * Default variation for Search Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SearchSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *Search*
 */
type SearchSliceVariation = SearchSliceDefault;

/**
 * Search Shared Slice
 *
 * - **API ID**: `search`
 * - **Description**: Search
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SearchSlice = prismic.SharedSlice<'search', SearchSliceVariation>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
	/**
	 * Text field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSlice = prismic.SharedSlice<'text', TextSliceVariation>;

/**
 * Primary content in *TextCentered → Default → Primary*
 */
export interface TextCenteredSliceDefaultPrimary {
	/**
	 * Text field in *TextCentered → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_centered.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for TextCentered Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextCenteredSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextCenteredSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextCentered*
 */
type TextCenteredSliceVariation = TextCenteredSliceDefault;

/**
 * TextCentered Shared Slice
 *
 * - **API ID**: `text_centered`
 * - **Description**: TextCentered
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextCenteredSlice = prismic.SharedSlice<'text_centered', TextCenteredSliceVariation>;

/**
 * Primary content in *TextColumns → Default → Primary*
 */
export interface TextColumnsSliceDefaultPrimary {
	/**
	 * Text Columns field in *TextColumns → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_columns.default.primary.text_columns
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text_columns: prismic.RichTextField;
}

/**
 * Default variation for TextColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextColumnsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextColumns*
 */
type TextColumnsSliceVariation = TextColumnsSliceDefault;

/**
 * TextColumns Shared Slice
 *
 * - **API ID**: `text_columns`
 * - **Description**: TextColumns
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextColumnsSlice = prismic.SharedSlice<'text_columns', TextColumnsSliceVariation>;

/**
 * Primary content in *TextWithImage → Default → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
	/**
	 * Text field in *TextWithImage → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * Image field in *TextWithImage → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextWithImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation = TextWithImageSliceDefault;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextWithImageSlice = prismic.SharedSlice<
	'text_with_image',
	TextWithImageSliceVariation
>;

/**
 * Primary content in *VideoGameSearch → Default → Primary*
 */
export interface VideoGameSearchSliceDefaultPrimary {
	/**
	 * Video Game Search field in *VideoGameSearch → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_game_search.default.primary.video_game_search
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	video_game_search: prismic.RichTextField;
}

/**
 * Default variation for VideoGameSearch Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoGameSearchSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<VideoGameSearchSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *VideoGameSearch*
 */
type VideoGameSearchSliceVariation = VideoGameSearchSliceDefault;

/**
 * VideoGameSearch Shared Slice
 *
 * - **API ID**: `video_game_search`
 * - **Description**: VideoGameSearch
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoGameSearchSlice = prismic.SharedSlice<
	'video_game_search',
	VideoGameSearchSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			NavigationDocument,
			NavigationDocumentData,
			NavigationDocumentDataLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			AllDocumentTypes,
			BgPageSplitCardsSlice,
			BgPageSplitCardsSliceDefaultPrimaryCardItem,
			BgPageSplitCardsSliceDefaultPrimary,
			BgPageSplitCardsSliceVariation,
			BgPageSplitCardsSliceDefault,
			DndSlice,
			DndSliceVariation,
			DndSliceDefault,
			FormSlice,
			FormSliceDefaultPrimary,
			FormSliceVariation,
			FormSliceDefault,
			GeekTriviaScoresSlice,
			GeekTriviaScoresSliceVariation,
			GeekTriviaScoresSliceDefault,
			GeekTriviaThemesSlice,
			GeekTriviaThemesSliceVariation,
			GeekTriviaThemesSliceDefault,
			GooglemapSlice,
			GooglemapSliceVariation,
			GooglemapSliceDefault,
			GridSelectSlice,
			GridSelectSliceDefaultPrimaryGridgroupItem,
			GridSelectSliceDefaultPrimary,
			GridSelectSliceVariation,
			GridSelectSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroSmallSlice,
			HeroSmallSliceDefaultPrimary,
			HeroSmallSliceVariation,
			HeroSmallSliceDefault,
			ImageSlice,
			ImageSliceDefaultPrimary,
			ImageSliceBannerPrimary,
			ImageSliceVariation,
			ImageSliceDefault,
			ImageSliceBanner,
			ImageCardsSlice,
			ImageCardsSliceDefaultPrimaryCardsItem,
			ImageCardsSliceDefaultPrimary,
			ImageCardsSliceVariation,
			ImageCardsSliceDefault,
			ImagewithtextSlice,
			ImagewithtextSliceDefaultPrimary,
			ImagewithtextSliceVariation,
			ImagewithtextSliceDefault,
			LargeResoSlice,
			LargeResoSliceVariation,
			LargeResoSliceDefault,
			PageSplitSlice,
			PageSplitSliceDefaultPrimary,
			PageSplitSliceVariation,
			PageSplitSliceDefault,
			PageSplitCardsSlice,
			PageSplitCardsSliceDefaultPrimaryCardsItem,
			PageSplitCardsSliceDefaultPrimary,
			PageSplitCardsSliceVariation,
			PageSplitCardsSliceDefault,
			ReservationSlice,
			ReservationSliceVariation,
			ReservationSliceDefault,
			SearchSlice,
			SearchSliceVariation,
			SearchSliceDefault,
			TextSlice,
			TextSliceDefaultPrimary,
			TextSliceVariation,
			TextSliceDefault,
			TextCenteredSlice,
			TextCenteredSliceDefaultPrimary,
			TextCenteredSliceVariation,
			TextCenteredSliceDefault,
			TextColumnsSlice,
			TextColumnsSliceDefaultPrimary,
			TextColumnsSliceVariation,
			TextColumnsSliceDefault,
			TextWithImageSlice,
			TextWithImageSliceDefaultPrimary,
			TextWithImageSliceVariation,
			TextWithImageSliceDefault,
			VideoGameSearchSlice,
			VideoGameSearchSliceDefaultPrimary,
			VideoGameSearchSliceVariation,
			VideoGameSearchSliceDefault
		};
	}
}
